#!/usr/bin/env bash

case "$2" in
    dhcp4-change)
        /usr/sbin/lliurex-autotags-network
    ;;

    up)
        /usr/sbin/lliurex-autotags-network
    ;;

    down)
        /usr/sbin/lliurex-autotags-network
    ;;

    *)
    ;;
esac
