#!/bin/sh

set -e

#DEBHELPER#

# we want to be AFTER debhelper
case "$1" in
   configure)

	systemctl --system daemon-reload >/dev/null || true
	RC=0
	deb-systemd-invoke status lliurex-auto-upgrade.service >/dev/null || RC=1

	if [ "$RC" = "1"  ];then
		deb-systemd-invoke start lliurex-auto-upgrade.service >/dev/null || true
	fi
	
   ;;

   abort-upgrade|abort-remove|abort-deconfigure)
   ;;

   *)
       exit 1
   ;;
esac


exit 0

